export const FETCH_ITEM_LIST_REQUEST = 'FETCH_ITEM_LIST_REQUEST'
export const FETCH_ITEM_LIST_SUCCESS = 'FETCH_ITEM_LIST_SUCCESS'
export const FETCH_ITEM_LIST_ERROR = 'FETCH_ITEM_LIST_ERROR'

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST'
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS'
export const FETCH_ITEM_ERROR = 'FETCH_ITEM_ERROR'

export const FETCH_DASHBOARD_REQUEST = 'FETCH_DASHBOARD_REQUEST'
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS'
export const FETCH_DASHBOARD_ERROR = 'FETCH_DASHBOARD_ERROR'

export const FETCH_KPI_REQUEST = 'FETCH_KPI_REQUEST'
export const FETCH_KPI_SUCCESS = 'FETCH_KPI_SUCCESS'
export const FETCH_KPI_ERROR = 'FETCH_KPI_ERROR'
